name: "Tests: Playwright"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
  FLAKINESS_CONNECTION_STRING: ${{ secrets.FLAKINESS_CONNECTION_STRING }}

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
      - name: Print job info
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          node --version
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install NPM modules
        run: npm install
      - name: Install Playwright dependencies
        run: npm run playwright:install
      - name: Run e2e tests
        run: |
          ./run_e2e_tests.js
      - name: Archive trace artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Playwright traces
          path: ./__tests__/playwright/traces